name: CI
on:
   push:
      branches: [ "main", "develop" ]
   pull_request:
      branches: [ "main" ]
      
jobs:
   build_job:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: installing
           run: sudo apt install cmake make g++

         - name: configure
           run: cmake -S . -B build

         - name: build
           run: cmake --build build
